# ConfigMap for Dog Walker Platform Backend Services
# Addresses requirement 7.4.2 Deployment Architecture: Environment-Specific Configuration Management
# This ConfigMap provides environment-specific configurations for backend services to ensure proper functionality and scalability

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
  labels:
    app: dog-walker-platform
    environment: production
data:
  # Application Environment
  APP_ENV: "production"
  LOG_LEVEL: "info"

  # Database Hosts
  REDIS_HOST: "redis.default.svc.cluster.local"
  POSTGRES_HOST: "postgres.default.svc.cluster.local"
  MONGODB_HOST: "mongodb.default.svc.cluster.local"

  # Service URLs
  API_GATEWAY_URL: "http://api-gateway-service.default.svc.cluster.local"
  AUTH_SERVICE_URL: "http://auth-service.default.svc.cluster.local"
  BOOKING_SERVICE_URL: "http://booking-service.default.svc.cluster.local"
  NOTIFICATION_SERVICE_URL: "http://notification-service.default.svc.cluster.local"
  PAYMENT_SERVICE_URL: "http://payment-service.default.svc.cluster.local"
  TRACKING_SERVICE_URL: "http://tracking-service.default.svc.cluster.local"

  # Note: Sensitive data like DATABASE_PASSWORD and API_KEY should be stored in Kubernetes Secrets
  # These placeholders are included here for reference but should be moved to a Secret resource
  DATABASE_PASSWORD: "secure_password_placeholder"
  API_KEY: "secure_api_key_placeholder"

  # Additional Configuration
  CORS_ALLOWED_ORIGINS: "*.dog-walker-platform.com"
  MAX_CONNECTIONS_PER_SERVICE: "100"
  REQUEST_TIMEOUT_MS: "5000"
  RETRY_ATTEMPTS: "3"
  RETRY_DELAY_MS: "1000"
  CACHE_TTL_SECONDS: "3600"
  MAX_UPLOAD_SIZE_MB: "10"
  GEOFENCE_RADIUS_KM: "25"
  BOOKING_WINDOW_MINUTES: "60"
  WALK_DURATION_MINUTES: "30,60,90"
  HEALTH_CHECK_INTERVAL_SECONDS: "30"