platform :ios, '13.0'

target 'DogWalker' do
  use_frameworks!

  pod 'Alamofire', '~> 5.6.4'
  pod 'Firebase/Analytics', '~> 10.6.0'
  pod 'GoogleMaps', '~> 7.3.0'
  pod 'Stripe', '~> 23.0.1'

  target 'DogWalkerTests' do
    inherit! :search_paths
  end

  target 'DogWalkerUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end