# Docker Compose configuration for development environment
# Addresses requirement: Backend Service Orchestration for Development (7.4.2 Deployment Architecture)

version: "3.8"

services:
  # API Gateway Service
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    container_name: ${COMPOSE_PROJECT_NAME:-dogwalker}_api_gateway_dev
    ports:
      - "${API_GATEWAY_PORT:-8080}:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:3000
      - BOOKING_SERVICE_URL=http://booking-service:8081
      - NOTIFICATION_SERVICE_URL=http://notification-service:8082
      - PAYMENT_SERVICE_URL=http://payment-service:8083
      - TRACKING_SERVICE_URL=http://tracking-service:8084
    volumes:
      - ./api-gateway:/app # Mount source code for development
      - /app/node_modules # Preserve container node_modules
    networks:
      - ${NETWORK_NAME:-dogwalker_network}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Authentication Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    container_name: ${COMPOSE_PROJECT_NAME:-dogwalker}_auth_service_dev
    expose:
      - "${AUTH_SERVICE_PORT:-3000}"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./auth-service:/app # Mount source code for development
      - /app/node_modules # Preserve container node_modules
    networks:
      - ${NETWORK_NAME:-dogwalker_network}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # Booking Service
  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    container_name: ${COMPOSE_PROJECT_NAME:-dogwalker}_booking_service_dev
    expose:
      - "${BOOKING_SERVICE_PORT:-8081}"
    environment:
      - BOOKING_SERVICE_PORT=8081
      - GO_ENV=development
    volumes:
      - ./booking-service:/app # Mount source code for development
      - /app/go/pkg # Preserve Go packages
    networks:
      - ${NETWORK_NAME:-dogwalker_network}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # Notification Service
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    container_name: ${COMPOSE_PROJECT_NAME:-dogwalker}_notification_service_dev
    expose:
      - "${NOTIFICATION_SERVICE_PORT:-8082}"
    environment:
      - NODE_ENV=development
      - NOTIFICATION_SERVICE_PORT=8082
    volumes:
      - ./notification-service:/app # Mount source code for development
      - /app/node_modules # Preserve container node_modules
    networks:
      - ${NETWORK_NAME:-dogwalker_network}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # Payment Service
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    container_name: ${COMPOSE_PROJECT_NAME:-dogwalker}_payment_service_dev
    expose:
      - "${PAYMENT_SERVICE_PORT:-8083}"
    environment:
      - NODE_ENV=development
      - PORT=8083
    volumes:
      - ./payment-service:/app # Mount source code for development
      - /app/node_modules # Preserve container node_modules
    networks:
      - ${NETWORK_NAME:-dogwalker_network}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # Tracking Service
  tracking-service:
    build:
      context: ./tracking-service
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    container_name: ${COMPOSE_PROJECT_NAME:-dogwalker}_tracking_service_dev
    expose:
      - "${TRACKING_SERVICE_PORT:-8084}"
    environment:
      - GO_ENV=development
      - TRACKING_WS_PORT=8084
    volumes:
      - ./tracking-service:/app # Mount source code for development
      - /app/go/pkg # Preserve Go packages
    networks:
      - ${NETWORK_NAME:-dogwalker_network}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

networks:
  dogwalker_network:
    name: ${NETWORK_NAME:-dogwalker_network}
    driver: bridge