# Human Tasks:
# 1. Ensure S3 bucket is created and properly configured for log storage
# 2. Configure AWS credentials for S3 access
# 3. Verify network connectivity between Loki and other monitoring components
# 4. Review and adjust retention periods based on compliance requirements
# 5. Set up appropriate authentication for Grafana access

# Requirement: Log Aggregation and Monitoring (Technical Specification/7.4 Cross-Cutting Concerns/7.4.1 Monitoring and Observability)
# Provides a centralized system for collecting, storing, and querying logs to enhance observability and debugging.

auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  replication_factor: 3
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
    - loki-memberlist

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    shared_store: s3
  aws:
    s3: 
      endpoint: s3.amazonaws.com
      region: us-east-1
      bucket_name: dogwalker-logs
      insecure: false
      sse_encryption: true
      http:
        idle_conn_timeout: 90s
        response_header_timeout: 30s
        insecure_skip_verify: false
        tls_handshake_timeout: 10s
        expect_continue_timeout: 1s
        max_idle_connections: 100
        max_idle_connections_per_host: 100
        max_retries: 5

compactor:
  working_directory: /var/loki/compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  retention_period: 30d
  enforce_metric_name: false
  max_entries_limit_per_query: 5000
  max_query_series: 500
  max_query_lookback: 720h
  max_query_length: 721h
  max_query_parallelism: 32
  cardinality_limit: 100000
  max_streams_per_user: 0
  max_global_streams_per_user: 0
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB

chunk_store_config:
  max_look_back_period: 720h
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 500MB
      validity: 24h

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

ruler:
  storage:
    type: local
    local:
      directory: /var/loki/rules
  rule_path: /var/loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_alertmanager_v2: true
  evaluation_interval: 1m
  poll_interval: 1m
  concurrent_executions: 10

distributor:
  ring:
    kvstore:
      store: memberlist
  ha_tracker:
    enable_ha_tracker: true
    kvstore:
      store: memberlist
    enable_for_all_users: true
    failover_timeout: 30s

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
    final_sleep: 0s
  chunk_idle_period: 1h
  chunk_target_size: 1536000
  max_chunk_age: 2h
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /var/loki/wal

querier:
  engine:
    timeout: 3m
    max_look_back_period: 720h
  query_ingesters_within: 2h
  query_store_after: 12h

frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  downstream_url: http://querier:3100
  max_outstanding_per_tenant: 2000

frontend_worker:
  frontend_address: frontend:9095
  grpc_client_config:
    max_send_msg_size: 104857600
    max_recv_msg_size: 104857600

analytics:
  reporting_enabled: false

tracing:
  enabled: true