# Requirement addressed: Continuous Integration and Deployment
# Location: Technical Specification/9.5 Development & Deployment/CI/CD Pipeline
# Automates the build, test, and deployment processes for the Android application.

name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8"
  ANDROID_COMPILE_SDK: 33
  ANDROID_BUILD_TOOLS: 33.0.1
  ANDROID_SDK: 21

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x src/android/gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build with Gradle
      working-directory: src/android
      run: ./gradlew build

    - name: Run Unit Tests
      working-directory: src/android
      run: ./gradlew test

    - name: Run Instrumented Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        working-directory: src/android
        script: ./gradlew connectedAndroidTest

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: src/android/app/build/outputs/apk/release/app-release.apk

  deploy:
    name: Deploy to Play Store
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: app-release

    - name: Setup Ruby for Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: Deploy to Play Store
      uses: maierj/fastlane-action@v3.0.0
      with:
        lane: 'deploy'
        subdirectory: 'src/android/fastlane'
      env:
        PLAY_STORE_JSON_KEY: ${{ secrets.PLAY_STORE_JSON_KEY }}

  notify:
    name: Notify Team
    needs: [build, deploy]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Send Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()